/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as PromoBase from '../src/components/Promo';
import * as PromoVariants from '../src/components/Promo.variants';

// Unknown identifier below should be ignored by resolver
export const componentMap = new Map<string, any>([
  // Spread base + variants into a single entry
  ['Promo', { ...PromoBase, ...PromoVariants }],
]);
