/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as OtherComponent1 from '../components/TestComponent';
import * as OtherComponent2 from '../components/TestComponent2';

export const components = new Map([
    ['OtherComponent1', OtherComponent1],
    ['OtherComponent2', OtherComponent2],
]);