/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as PromoBase from '../components/Promo';
import * as PromoVariants from '../components/Promo.variants';

export const components = new Map([
  ['PromoBaseOnly', PromoBase],
  ['PromoVariantsOnly', PromoVariants],
]);
