# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - dev
    - release/*
  paths:
    include:
    - /

# should trigger builds for PRs targeting any of the listed branches
pr:
  branches:
    include:
    - master
    - dev
    - release/*
  paths:
    include:
    - /

pool:
  vmImage: 'ubuntu-latest'

variables:
  shouldPublish: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/dev'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
    lernaSinceFlag: "--since=origin/dev"
# disable `PublishCodeCoverageResults` report generation, as `reportgenerator` provides custom report
  disable.coverage.autogenerate: 'true'
# Some steps here scaffold jss apps and check if they build and lint correctly
# build apps step currently excluded: RAV apps have issues with yarn build, nextjs has some with all builds without Sitecore connection
# TODO: add step for lerna run build --scope sample-* when RAV and nextjs yarn build issues are resolved

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
- script: |
    git status
    git remote -v
    git branch -a
- script: |
    git config user.email builds@sitecore.com
    git config user.name "Automated Build"
    git remote set-url origin https://$GITHUB_PAT_ENV@github.com/Sitecore/xmc-jss-dev.
    git fetch --all
    git checkout $(branchName)
  displayName: 'apply git configuration'
  env:
    GITHUB_PAT_ENV: $(GITHUB-PAT)


