/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as TestComponent from '../components/TestComponent';
import * as Test2 from '../../node_modules/TestComponent2';
import * as fs from 'node:fs';

export const components = new Map([
    ['TestComponent', TestComponent],
    ['Test2', Test2],
]);

export default components;