/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import { Component3 } from '../src/components/TestComponent3';

export const components = new Map([['Component3', Component3]]);

export default components;
