// This file is generated by the Sitecore CLI. Do not edit by hand.
// Run: npm run sitecore-tools:generate-map

import type { Type } from '@angular/core';
import type { AngularModule, ComponentMap } from '@sitecore-content-sdk/angular';
import { ScFormComponent } from '@sitecore-content-sdk/angular';
import { ColumnSplitterComponent } from 'components/column-splitter.component';
import { ContainerComponent } from 'components/container.component';
import { ContentBlockComponent } from 'components/content-block.component';
import { ImageComponent } from 'components/image.component';
import { LinkListComponent } from 'components/link-list.component';
import { NavigationComponent } from 'components/navigation.component';
import { PageContentComponent } from 'components/page-content.component';
import { PromoComponent } from 'components/promo.component';
import { RichTextComponent } from 'components/rich-text.component';
import { RowSplitterComponent } from 'components/row-splitter.component';
import { TitleComponent } from 'components/title.component';

export const componentMap: ComponentMap = new Map<string, Type<unknown> | AngularModule>([
  ['ColumnSplitter', ColumnSplitterComponent],
  ['Container', ContainerComponent],
  ['ContentBlock', ContentBlockComponent],
  ['Image', ImageComponent],
  ['LinkList', LinkListComponent],
  ['Navigation', NavigationComponent],
  ['PageContent', PageContentComponent],
  ['PartialDesignDynamicPlaceholder', ContainerComponent],
  ['Promo', PromoComponent],
  ['RichText', RichTextComponent],
  ['RowSplitter', RowSplitterComponent],
  ['Title', TitleComponent],
  ['Form', ScFormComponent],
]);

export default componentMap;
