import { shadcnComponents } from '@json-render/shadcn';
import { defineAtomsCatalog, defineAtomsRegistry } from '@sitecore-content-sdk/nextjs';
import { shadcnComponentDefinitions } from '@json-render/shadcn';
import { z } from 'zod';
import { Heading, HeadingSchema } from './components/Heading';
import {
  // display — re-implemented
  Text,
  TextSchema,
  Button,
  ButtonSchema,
  Badge,
  BadgeSchema,
  Alert,
  AlertSchema,
  Avatar,
  AvatarSchema,
  Image,
  ImageSchema,
  Separator,
  SeparatorSchema,
  Progress,
  ProgressSchema,
  Skeleton,
  SkeletonSchema,
  Link,
  LinkSchema,
  // complex — wrapped
  Tabs,
  TabsSchema,
  Accordion,
  AccordionSchema,
  CollapsibleComp,
  CollapsibleSchema,
  Pagination,
  PaginationSchema,
  Dialog,
  DialogSchema,
  Drawer,
  DrawerSchema,
  Popover,
  PopoverSchema,
  Tooltip,
  TooltipSchema,
  DropdownMenu,
  DropdownMenuSchema,
  Carousel,
  CarouselSchema,
  Table,
  TableSchema,
  Input,
  InputSchema,
  Textarea,
  TextareaSchema,
  Select,
  SelectSchema,
  Checkbox,
  CheckboxSchema,
  Radio,
  RadioSchema,
  Switch,
  SwitchSchema,
  Slider,
  SliderSchema,
  Toggle,
  ToggleSchema,
  ToggleGroupComp,
  ToggleGroupSchema,
  ButtonGroup,
  ButtonGroupSchema,
} from './components/overrides';

export const catalog = defineAtomsCatalog({
  version: '1.0.0',
  components: {
    Test: {
      version: '1.0.1',
      props: z.object({
        text: z.string().default('Hello World!!'),
      }),
    },
    Card: shadcnComponentDefinitions.Card,
    Stack: shadcnComponentDefinitions.Stack,
    Grid: shadcnComponentDefinitions.Grid,
    Heading: { ...shadcnComponentDefinitions.Heading, props: HeadingSchema },
    Text: { ...shadcnComponentDefinitions.Text, props: TextSchema },
    Button: { ...shadcnComponentDefinitions.Button, props: ButtonSchema },
    Badge: { ...shadcnComponentDefinitions.Badge, props: BadgeSchema },
    Alert: { ...shadcnComponentDefinitions.Alert, props: AlertSchema },
    Avatar: { ...shadcnComponentDefinitions.Avatar, props: AvatarSchema },
    Image: { ...shadcnComponentDefinitions.Image, props: ImageSchema },
    Separator: { ...shadcnComponentDefinitions.Separator, props: SeparatorSchema },
    Progress: { ...shadcnComponentDefinitions.Progress, props: ProgressSchema },
    Skeleton: { ...shadcnComponentDefinitions.Skeleton, props: SkeletonSchema },
    Link: { ...shadcnComponentDefinitions.Link, props: LinkSchema },
    Tabs: { ...shadcnComponentDefinitions.Tabs, props: TabsSchema },
    Accordion: { ...shadcnComponentDefinitions.Accordion, props: AccordionSchema },
    Collapsible: { ...shadcnComponentDefinitions.Collapsible, props: CollapsibleSchema },
    Pagination: { ...shadcnComponentDefinitions.Pagination, props: PaginationSchema },
    Dialog: { ...shadcnComponentDefinitions.Dialog, props: DialogSchema },
    Drawer: { ...shadcnComponentDefinitions.Drawer, props: DrawerSchema },
    Popover: { ...shadcnComponentDefinitions.Popover, props: PopoverSchema },
    Tooltip: { ...shadcnComponentDefinitions.Tooltip, props: TooltipSchema },
    DropdownMenu: { ...shadcnComponentDefinitions.DropdownMenu, props: DropdownMenuSchema },
    Carousel: { ...shadcnComponentDefinitions.Carousel, props: CarouselSchema },
    Table: { ...shadcnComponentDefinitions.Table, props: TableSchema },
    Input: { ...shadcnComponentDefinitions.Input, props: InputSchema },
    Textarea: { ...shadcnComponentDefinitions.Textarea, props: TextareaSchema },
    Select: { ...shadcnComponentDefinitions.Select, props: SelectSchema },
    Checkbox: { ...shadcnComponentDefinitions.Checkbox, props: CheckboxSchema },
    Radio: { ...shadcnComponentDefinitions.Radio, props: RadioSchema },
    Switch: { ...shadcnComponentDefinitions.Switch, props: SwitchSchema },
    Slider: { ...shadcnComponentDefinitions.Slider, props: SliderSchema },
    Toggle: { ...shadcnComponentDefinitions.Toggle, props: ToggleSchema },
    ToggleGroup: { ...shadcnComponentDefinitions.ToggleGroup, props: ToggleGroupSchema },
    ButtonGroup: { ...shadcnComponentDefinitions.ButtonGroup, props: ButtonGroupSchema },
  },
  actions: {},
});

export const registry = defineAtomsRegistry(catalog, {
  components: {
    Test: ({ props }) => {
      return <div>{props.text}</div>;
    },
    // Layout — shadcn already supports className on these
    Card: shadcnComponents.Card,
    Stack: shadcnComponents.Stack,
    Grid: shadcnComponents.Grid,
    // All others — local overrides with className support
    Heading,
    Text,
    Button,
    Badge,
    Alert,
    Avatar,
    Image,
    Separator,
    Progress,
    Skeleton,
    Link,
    Tabs,
    Accordion,
    Collapsible: CollapsibleComp,
    Pagination,
    Dialog,
    Drawer,
    Popover,
    Tooltip,
    DropdownMenu,
    Carousel,
    Table,
    Input,
    Textarea,
    Select,
    Checkbox,
    Radio,
    Switch,
    Slider,
    Toggle,
    ToggleGroup: ToggleGroupComp,
    ButtonGroup,
  },
  actions: {},
});

