/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as TestComponent from '@comps/TestComponent';

export const components = new Map([
    ['TestComponent', TestComponent],
]);

export default components;
