/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as TestComponent from '../src/components/TestComponent';
import * as TestComponent2 from '../src/components/TestComponent2';

const components = new Map([
    ['TestComponent', TestComponent],
]);

components.set('TestComponent2', TestComponent2);

export default components;
