/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as TestComponent from '../src/components/TestComponent';
import { Component1 } from '../src/components/TestComponent2';
import { Component2 } from '../src/components/TestComponent2';

export const components = new Map([
    ['TestComponent', TestComponent],
    ['Component1', Component1],
    ['Component2', Component2],
]);

export default components;