/**
 * Generates src/environments/environment.dev.ts or environment.prod.ts
 * by reading dotenv files into process.env and serializing the values the
 * Sitecore SDK packages expect at runtime.
 *
 * Usage:
 *   tsx scripts/generate-environment.ts --dev   (loads .env then .env.dev)
 *   tsx scripts/generate-environment.ts --prod  (loads .env then .env.prod)
 *
 * Priority: real process.env > mode-specific .env file > base .env file.
 */
import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import dotenv from 'dotenv';

const projectRoot = process.cwd();
const envDir = resolve(projectRoot, 'src', 'environments');

function loadEnvFiles(mode: 'dev' | 'prod'): void {
  const modeFile = mode === 'dev' ? '.env.dev' : '.env.prod';

  // Base .env first — does NOT override existing process.env values
  const basePath = resolve(projectRoot, '.env');
  if (existsSync(basePath)) {
    dotenv.config({ path: basePath, override: false });
  }

  // Mode-specific file — overrides values from .env (but not real process.env)
  const modePath = resolve(projectRoot, modeFile);
  if (existsSync(modePath)) {
    dotenv.config({ path: modePath, override: true });
  }
}

function env(key: string, fallback = ''): string {
  return process.env[key] ?? fallback;
}

/**
 * All env vars that the Sitecore SDK packages read from process.env.
 * See:
 *  - packages/content/src/config/define-config.ts  (getFallbackConfig)
 *  - packages/core/src/tools/resolve-edge-url.ts
 *  - packages/core/src/tools/utils.ts
 */
function serialize(production: boolean): string {
  return `\
/**
 * Auto-generated by scripts/generate-environment.ts — do not edit.
 * Mode: ${production ? 'production' : 'development'}
 */
export const environment = {
  production: ${production},
  sitecore: {
    edgeContextId: ${JSON.stringify(env('SITECORE_EDGE_CONTEXT_ID'))},
    edgeClientContextId: ${JSON.stringify(env('SITECORE_EDGE_CLIENT_CONTEXT_ID'))},
    edgePlatformHostname: ${JSON.stringify(env('SITECORE_EDGE_PLATFORM_HOSTNAME'))},
    experienceEdgeHostname: ${JSON.stringify(env('SITECORE_EXPERIENCE_EDGE_HOSTNAME'))},
    apiKey: ${JSON.stringify(env('SITECORE_API_KEY'))},
    apiHost: ${JSON.stringify(env('SITECORE_API_HOST'))},
    editingSecret: ${JSON.stringify(env('SITECORE_EDITING_SECRET'))},
    defaultSite: ${JSON.stringify(env('SITECORE_DEFAULT_SITE'))},
    defaultLanguage: ${JSON.stringify(env('SITECORE_DEFAULT_LANGUAGE', 'en'))},
    personalizeScope: ${JSON.stringify(env('SITECORE_PERSONALIZE_SCOPE'))},
    personalizeEdgeTimeout: ${JSON.stringify(env('PERSONALIZE_MIDDLEWARE_EDGE_TIMEOUT'))},
    personalizeCdpTimeout: ${JSON.stringify(env('PERSONALIZE_MIDDLEWARE_CDP_TIMEOUT'))},
    jssAllowedOrigins: ${JSON.stringify(env('JSS_ALLOWED_ORIGINS'))},
  },
};
`;
}

function parseMode(): 'dev' | 'prod' {
  const args = process.argv.slice(2);
  if (args.includes('--dev')) return 'dev';
  if (args.includes('--prod')) return 'prod';
  console.error('Usage: tsx scripts/generate-environment.ts --dev | --prod');
  process.exit(1);
}

function main(): void {
  const mode = parseMode();
  loadEnvFiles(mode);

  const production = mode === 'prod';
  const outFile = production ? 'environment.prod.ts' : 'environment.dev.ts';
  const outPath = resolve(envDir, outFile);
  writeFileSync(outPath, serialize(production), 'utf8');
  console.log(`[gen:env] Wrote ${outFile} (mode=${mode})`);
}

main();
