/**
 * Generates src/environments/environment.dev.ts or environment.prod.ts
 * by reading process.env populated by dotenv
 * and serializing every key in process.env verbatim (after dotenv). The inherited shell
 * environment is included, so CI may want a clean env or a wrapper that filters keys.
 *
 * Usage:
 *   tsx scripts/generate-environment.ts --dev   (loads .env then .env.dev)
 *   tsx scripts/generate-environment.ts --prod  (loads .env then .env.prod)
 *
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import dotenv from 'dotenv';

const projectRoot = process.cwd();
const angularEnvDir = resolve(projectRoot, 'src', 'environments');

function loadEnvFiles(mode: 'dev' | 'prod'): void {
  const contextEnvFile = mode === 'dev' ? '.env.dev' : '.env.prod';

  // Base .env first — does NOT override existing process.env values
  const baseEnvPath = resolve(projectRoot, '.env');
  const localEnvPath = resolve(projectRoot, '.env.local');
  const contextEnvPath = resolve(projectRoot, contextEnvFile);
  dotenv.config({ path: [baseEnvPath, localEnvPath, contextEnvPath] });
}

/**
 * Snapshots all keys in `process.env` (after dotenv) into a typed object literal.
 * Skips a string key named `production` so it does not collide with Angular's boolean `production`.
 */
function serialize(production: boolean): string {
  const lines: string[] = [
    `  production: "${production}",`,
    `  NODE_ENV: ${JSON.stringify(process.env.NODE_ENV)},`,
  ];

  const keys = Object.keys(process.env).sort();
  for (const key of keys) {
    if (key === 'NODE_ENV') {
      continue;
    }
    if (key === 'production') {
      continue;
    }
    const value = process.env[key] ?? '';
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
  }

  return `\
/**
 * Auto-generated by scripts/generate-environment.ts — do not edit.
 * Mode: ${production ? 'production' : 'development'}
 * Keys mirror process.env after loading .env (see script header).
 */
export const environment = {
${lines.join('\n')}
};
`;
}

function parseMode(): 'dev' | 'prod' {
  const args = process.argv.slice(2);
  if (args.includes('--dev')) return 'dev';
  if (args.includes('--prod')) return 'prod';
  console.error('Usage: tsx scripts/generate-environment.ts --dev | --prod');
  process.exit(1);
}

function main(): void {
  const mode = parseMode();
  loadEnvFiles(mode);

  const production = mode === 'prod';
  const outFile = production ? 'environment.prod.ts' : 'environment.dev.ts';
  const outPath = resolve(angularEnvDir, outFile);
  writeFileSync(outPath, serialize(production), 'utf8');
  console.log(`[content-sdk:prebuild] Wrote ${outFile} (mode=${mode})`);
}

main();
