// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
import { ImportEntry } from '@sitecore-content-sdk/core/codegen';
// end of built-in imports

const importMap: ImportEntry[] = [];

export default combineImportEntries(defaultImportEntries, importMap);
