name: Bundle size and Test coverage

on:
  pull_request:
    branches: [dev]

jobs:
  check-bundle-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for full git history & branch comparison

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          yarn cache clean --all
          yarn install --immutable

      # 🔹 BUNDLE SIZE
      - name: Run bundle size comparison
        run: node ./scripts/check-next-bundle.js

      - name: Post PR comment (bundle size)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: bundle-size
          path: bundle-size-report.md
